CREATE DATABASE ProjetoFornecimento;
USE ProjetoFornecimento;

CREATE TABLE FORNECEDOR (
    COD_FORNECEDOR INT PRIMARY KEY,
    NOME_FORNECEDOR VARCHAR(100),
    STATUS_FORNECEDO VARCHAR(20) DEFAULT 'Ativo',
    CIDADE_FORNECEDOR VARCHAR(100)
);

CREATE TABLE PECA (
    COD_PECA INT PRIMARY KEY,
    NOME_PECA VARCHAR(100) NOT NULL,
    COR_PECA VARCHAR(50) NOT NULL,
    PESO_PECA DECIMAL(10,2) NOT NULL,
    CIDADE_PECA VARCHAR(100) NOT NULL
);

CREATE TABLE INSTITUICAO (
    COD_INSTITUICAO INT PRIMARY KEY,
    NOME_INSTITUICAO VARCHAR(100)
);

CREATE TABLE PROJETO (
    COD_PROJETO INT PRIMARY KEY,
    NOME_PROJETO VARCHAR(100),
    CIDADE_PROJETO VARCHAR(100),
    Icod INT,
    FOREIGN KEY (Icod) REFERENCES INSTITUICAO(COD_INSTITUICAO)
);

CREATE TABLE FORNECIMENTO (
    COD_FORNECIMENTO INT,
    COD_PECA INT,
    COD_PROJETO INT,
    QUANTIDADE_FORNECIMENTO INT,
    PRIMARY KEY (COD_FORNECIMENTO, COD_PECA, COD_PROJETO),
    FOREIGN KEY (COD_FORNECIMENTO) REFERENCES FORNECEDOR(COD_FORNECEDOR),
    FOREIGN KEY (COD_PECA) REFERENCES PECA(COD_PECA),
    FOREIGN KEY (COD_PROJETO) REFERENCES PROJETO(COD_PROJETO)
);

CREATE TABLE CIDADE (
    COD_CIDADE INT PRIMARY KEY,
    NOME_CIDADE VARCHAR(100),
    UF CHAR(2)
);

ALTER TABLE Fornecedor
ADD Fone VARCHAR(20);

ALTER TABLE Fornecedor
ADD Ccod INT;

ALTER TABLE Fornecedor
ADD CONSTRAINT FK_Fornecedor_Cidade FOREIGN KEY (Ccod) REFERENCES Cidade(Ccod);

-- Opcional: remover a coluna antiga "Cidade"
ALTER TABLE Fornecedor
DROP COLUMN Cidade;

ALTER TABLE Peca
ADD Ccod INT;

ALTER TABLE Peca
ADD CONSTRAINT FK_Peca_Cidade FOREIGN KEY (Ccod) REFERENCES Cidade(Ccod);

ALTER TABLE Peca
DROP COLUMN Cidade;

ALTER TABLE Projeto
ADD Ccod INT;

ALTER TABLE Projeto
ADD CONSTRAINT FK_Projeto_Cidade FOREIGN KEY (Ccod) REFERENCES Cidade(Ccod);

ALTER TABLE Projeto
DROP COLUMN Cidade;

ALTER TABLE Projeto
DROP FOREIGN KEY Projeto_ibfk_1;  -- ou o nome exato da constraint

ALTER TABLE Projeto
DROP COLUMN Icod;

DROP TABLE Instituicao;